# Generated by Django 5.0.7 on 2025-03-26 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venueimage',
            name='caption',
            field=models.CharField(blank=True, help_text='Optional caption for the image', max_length=255),
        ),
        migrations.AddField(
            model_name='venueimage',
            name='is_cover',
            field=models.BooleanField(default=False, help_text='Designate this image as the cover image (shown at the top of venue detail page)'),
        ),
    ]
