# Generated by Django 5.0.7 on 2025-05-04 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0002_venueimage_caption_venueimage_is_cover'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Availability',
        ),
    ]
