# Generated by Django 5.0.7 on 2025-04-23 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('regular', 'Regular User'), ('venue_manager', 'Venue Manager')], default='regular', max_length=20),
        ),
    ]
