# Generated by Django 5.0.7 on 2025-04-23 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationsetting',
            name='messages',
        ),
        migrations.DeleteModel(
            name='ChatMessage',
        ),
    ]
